### ISSUE TITLE
how to change parameters in query.yaml

### ISSUE THREAD

**Issue by 4ff4n** [Roboteq-Inc/ROS-Driver#8]
HI,
i am trying to use  Roboteq-Inc /ROS-Driver for my Differential drive robot. when i launch the driver.launch file. i see the  only left motor running at turtle speed. and the right motor not moving at all though the motors are are perfectly configured with Roborun+.
i would highly appreciate if some could help me tweaking the parameters at least i need to increase the motor speed at first?

looking forward to a kind response.

Thanks in advance

**Comment by zhughesjd** [comment]
Greeting Roboteq,
I am having the exact same issues as @4ff4n above.
One motor barely turns and the other motor has no response.
I am using the SDC2160 with the updated SDC21XX-Firmware-Update-v201-111419 driver.
How do we tweak the the  roboteq_motor_controller_driver/config/query.yaml file?

**Comment by 4ff4n** [comment]
> 
> 
> Greeting Roboteq,
> I am having the exact same issues as @4ff4n above.
> One motor barely turns and the other motor has no response.
> I am using the SDC2160 with the updated SDC21XX-Firmware-Update-v201-111419 driver.
> How do we tweak the the roboteq_motor_controller_driver/config/query.yaml file?

Hello @zhughesjd , Please try adding  scaling factor in your roboteq_motor_controller_driver_node.cpp file inside Driver::cmd_vel_callback: 

**cmd_sub << "!G 1" << " " << msg.linear.x * 125 << "_" << "!G 2" << " " << msg.angular.z * 250 << "_";**

Hope it would help cheers!

**Comment by zhughesjd** [comment]
@4ff4n, thanks a lot for this hint.
This helped.
